title: YKJ's Blog
description: "一个二次元风格的个人博客"
avatar: /assets/images/avatar.jpg
author: YKJ
github_username: mmkzn
email: 

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

repository: mmkzn/mmkzn.github.io
future: true

paginate: 5
paginate_path: /page:num/

timezone: Asia/Shanghai

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: YKJ
